# Generated by Django 5.0.6 on 2026-08-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
