# Generated by Django 5.0.6 on 2026-08-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_registration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceprofile',
            name='face_image',
        ),
    ]
