# Generated by Django 5.0.6 on 2026-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='trainers/default.png', null=True, upload_to='trainers/'),
        ),
    ]
