# Generated by Django 5.0.6 on 2026-07-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_image',
        ),
    ]
