# Generated by Django 5.0.6 on 2026-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_attendance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LEAVE', 'Leave'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20),
        ),
    ]
