# Generated by Django 5.0.6 on 2026-08-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
