name: Deploy Face Recognization Attendance Portal

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.12"

      - name: Deploy

        uses: appleboy/ssh-action@v1.2.2

        with:

          host: ${{ secrets.SERVER_IP }}

          username: ${{ secrets.SERVER_USER }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          port: ${{ secrets.SERVER_SSH_PORT }}

          script: |

            cd /home/user/AttendancePortal

            git fetch --all

            git reset --hard origin/main

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate --noinput

            python manage.py collectstatic --noinput

            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S systemctl restart attendanceportal

            sudo systemctl status attendance --no-pager